### ISSUE TITLE
SD1 optimized? 

### ISSUE THREAD

**Issue by ClashSAN** [symisc/tiny-dream#1]
Hi there, this project sounds very exciting! 
Particularly having fast, memory efficient inference on low ram android smartphones.

SD2 is mentioned, was SD1 architecture optimized for this library as well?

**Comment by symisc** [comment]
Hello,
Actually, **we reverted back to a Stable Diffusion 1.x implementation using the [CLIP transformer](https://openai.com/research/clip) for token embedding, 512*512 pixels output that can be [upscaled](https://pixlab.io/tiny-dream.html#features) to 2048x2048 high resolution output**.
