### ISSUE TITLE
Pre-Trained Models And Assets Missing

### ISSUE THREAD

**Issue by CycloneRing** [symisc/tiny-dream#10]
Hi, Link in your site is broken :

> Something went wrong
> Please try again later. If the issue persists, you can contact our support team using the button below.
> error code: E-403

**Comment by symisc** [comment]
Hello , 
     
     
      
     
    
      Are you ordering the package from Russia? If so, you cannot place an order due to the current situation... 
     
     
      
     
    
    
     
      
       
      
     
    
    
    
     
     
       On Tuesday, Oct 31, 2023 at 12:43 PM, Cyclone ***@***.***> wrote: 
       
      
      
       
      Hi, Link in your site is broken : 
       
       Something went wrongPlease try again later. If the issue persists, you can contact our support team using the button below.error code: E-403 
       
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/symisc/tiny-dream/issues/10","url": "https://github.com/symisc/tiny-dream/issues/10","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
