### ISSUE TITLE
When is the release date?

### ISSUE THREAD

**Issue by JianbangZ** [symisc/tiny-dream#2]
Official website says June/July 2023. Thanks

**Comment by symisc** [comment]
Hi Jim, 
     
     
      
     
    
      Few days. We are polishing the docs. 
     
     
      
     
    
      Thanks for your patience. 
     
     
      
     
    
    
     
      
       
       
         -- 
        Mrad - Symisc Systems. 
        
       
      
      
       
      
     
    
    
    
     
     
       On Monday, Jul 31, 2023 at 10:50 PM, Jim Zhang ***@***.***> wrote: 
       
      
      
       
      Official website says June/July 2023. Thanks 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/symisc/tiny-dream/issues/2","url": "https://github.com/symisc/tiny-dream/issues/2","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by JianbangZ** [comment]
> Hi Jim, Few days. We are polishing the docs. Thanks for your patience.
> […](#)
> -- Mrad - Symisc Systems. On Monday, Jul 31, 2023 at 10:50 PM, Jim Zhang ***@***.***> wrote: Official website says June/July 2023. Thanks —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "#2","url": "#2","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

Looking forward to it. A quick question, the inference speed showing on the offical website (several seconds), is it single step speed?

**Comment by symisc** [comment]
Yes @JianbangZ. The benchmarks speed shown on the website are for single SD inference step.

**Comment by symisc** [comment]
Tiny Dream 1.7.5 Released - https://github.com/symisc/tiny-dream/releases/tag/1.7.5
