### ISSUE TITLE
Is purchasing a USD$29 model is required to run this "opensource" software?

### ISSUE THREAD

**Issue by ianscrivener** [symisc/tiny-dream#4]
Please confirm that I cannot try this "opensource" Stablediffusion software without purchasing a USD$29 model from Symisc/Pixlab?

**Comment by symisc** [comment]
No, you can **convert stable diffusion ONNX models to ncnn models** without purchasing the [pre-trained models](https://pixlab.io/tiny-dream#downloads) from PixLab.
