### ISSUE TITLE
Issue building the current library

### ISSUE THREAD

**Issue by marcpre** [symisc/tiny-dream#5]
Hello,

when trying to build the boilerplate code I get the following error:

```
admin@admin-VirtualBox:~/Desktop/Code/_tinyDream_Model/build$ make
[ 50%] Building CXX object CMakeFiles/PIXLAB_TINY_DREAM.dir/boilerplate.cpp.o
In file included from /home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:75,
                 from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_bmp_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  514 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_bmp(const char*, int, int, int, const void*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  522 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_tga_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  613 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_tga(const char*, int, int, int, const void*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  621 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_hdr_to_func(void (*)(void*, void*, int), void*, int, int, int, const float*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  789 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_hdr(const char*, int, int, int, const float*)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
  796 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_jpg_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*, int)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
 1609 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_jpg(const char*, int, int, int, const void*, int)’:
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]
 1618 |    stbi__write_context s = { 0 };
      |                                ^
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]
/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘constexpr void tinyDream::_log(const string&) const’:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:85:17: error: call to non-‘constexpr’ function ‘std::function<_Res(_ArgTypes ...)>::operator bool() const [with _Res = void; _ArgTypes = {const char*, int, void*}]’
   85 |         if (xLog) {
      |                 ^
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘std::string tinyDream::randomString(int)’:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:102:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
  102 |         return std::move(out);
      |                ~~~~~~~~~^~~~~
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:102:25: note: remove ‘std::move’ call
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘ncnn::Mat tinyDream::getTextEmbedding(ncnn::Net&, std::string)’:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:487:50: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::vector<int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  487 |         for (auto it_tokenized = 0; it_tokenized < tokenized.size(); it_tokenized++)
      |                                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: At global scope:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 4 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]
  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)
      |      ^~~~~~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here
  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);
      |          ^~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 5 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]
  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)
      |      ^~~~~~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here
  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);
      |          ^~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 6 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]
  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)
      |      ^~~~~~~~~
In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:
/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here
  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);
      |          ^~~~~
/home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp: In function ‘void logCallback(const char*, int, void*)’:
/home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:46:7: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   46 |  write(STDOUT_FILENO, static_cast<const void*>(zLogMsg), static_cast<size_t>(msgLen));
      |  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/PIXLAB_TINY_DREAM.dir/build.make:63: CMakeFiles/PIXLAB_TINY_DREAM.dir/boilerplate.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/PIXLAB_TINY_DREAM.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

It seems that there are errors in the tinydream.hpp file.

I am on this machine:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
```

Any suggestions how to fix them?

**Comment by symisc** [comment]
Which compiler are using? Try integrating boilerplate.cpp and tinydream.hpp directly on your source tree without using the CMake build template. 
     
     
      
     
    
    
     
      
       
      
     
    
    
    
     
     
       On Thursday, Aug 31, 2023 at 8:51 PM, marcpre ***@***.***> wrote: 
       
      
      
       
      Hello, 
      when trying to build the boilerplate code I get the following error: 
      ***@***.***:~/Desktop/Code/_tinyDream_Model/build$ make[ 50%] Building CXX object CMakeFiles/PIXLAB_TINY_DREAM.dir/boilerplate.cpp.oIn file included from /home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:75,                 from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_bmp_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  514 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:514:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_bmp(const char*, int, int, int, const void*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  522 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:522:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_tga_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  613 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:613:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_tga(const char*, int, int, int, const void*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  621 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:621:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_hdr_to_func(void (*)(void*, void*, int), void*, int, int, int, const float*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  789 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:789:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_hdr(const char*, int, int, int, const float*)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers]  796 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:796:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_jpg_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*, int)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers] 1609 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1609:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h: In function ‘int stbi_write_jpg(const char*, int, int, int, const void*, int)’:/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::context’ [-Wmissing-field-initializers] 1618 |    stbi__write_context s = { 0 };      |                                ^/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::buffer’ [-Wmissing-field-initializers]/home/admin/Desktop/Code/_tinyDream_Model/stb_image_write.h:1618:32: warning: missing initializer for member ‘stbi__write_context::buf_used’ [-Wmissing-field-initializers]In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘constexpr void tinyDream::_log(const string&) const’:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:85:17: error: call to non-‘constexpr’ function ‘std::function<_Res(_ArgTypes ...)>::operator bool() const [with _Res = void; _ArgTypes = {const char*, int, void*}]’   85 |         if (xLog) {      |                 ^/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘std::string tinyDream::randomString(int)’:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:102:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]  102 |         return std::move(out);      |                ~~~~~~~~~^~~~~/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:102:25: note: remove ‘std::move’ callIn file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: In member function ‘ncnn::Mat tinyDream::getTextEmbedding(ncnn::Net&, std::string)’:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:487:50: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::vector<int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]  487 |         for (auto it_tokenized = 0; it_tokenized < tokenized.size(); it_tokenized  )      |                                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp: At global scope:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 4 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)      |      ^~~~~~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);      |          ^~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 5 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)      |      ^~~~~~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);      |          ^~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:618:6: error: default argument given for parameter 6 of ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ [-fpermissive]  618 | bool tinyDream::dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30)      |      ^~~~~~~~~In file included from /home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:14:/home/admin/Desktop/Code/_tinyDream_Model/tinydream.hpp:193:10: note: previous specification in ‘bool tinyDream::dream(const string&, const string&, std::string&, bool, int, int)’ here  193 |     bool dream(const std::string& positivePrompt, const std::string& negativePrompt, std::string& outputImgPath, bool upScale = true, int seed = 42, int step = 30);      |          ^~~~~/home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp: In function ‘void logCallback(const char*, int, void*)’:/home/admin/Desktop/Code/_tinyDream_Model/boilerplate.cpp:46:7: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]   46 |  write(STDOUT_FILENO, static_cast<const void*>(zLogMsg), static_cast<size_t>(msgLen));      |  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~make[2]: *** [CMakeFiles/PIXLAB_TINY_DREAM.dir/build.make:63: CMakeFiles/PIXLAB_TINY_DREAM.dir/boilerplate.cpp.o] Error 1make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/PIXLAB_TINY_DREAM.dir/all] Error 2make: *** [Makefile:84: all] Error 2 
      It seems that there are errors in the tinydream.hpp file. 
      I am on this machine: 
      Distributor ID: UbuntuDescription:    Ubuntu 20.04.6 LTSRelease:        20.04 
      Any suggestions how to fix them? 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/symisc/tiny-dream/issues/5","url": "https://github.com/symisc/tiny-dream/issues/5","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
