### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by appvoid** [symisc/tiny-dream#7]
I've already purchased and downloaded the model package. Still not able to compile. Seems to be a little difficult for entry level. Hopefully you share how did you manage to compile all of this.

**Comment by appvoid** [comment]
I've already purchased and downloaded the model package. Still not able to compile. Seems to be a little difficult for entry level. Hopefully you share how did you manage to compile all of this.

**Comment by symisc** [comment]
Hello,

[Tiny Dream](https://pixlab.io/tiny-dream#building-td) it self is just a single C++ header file. Nothing complicated with it, you [just drop](https://pixlab.io/tiny-dream#building-td) that header file on your source tree, and you are done. What is tricky is the backend tensor library deployment (ncnn in our case). Refer to the [How to Build](https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-windows-x64-using-visual-studio-community-2017) section of the ncnn documentation for additional information.

**Comment by appvoid** [comment]
I cannot believe that I just paid ~30 dollars and this is all the support I get. I already told you I wasn't able to compile anything. I watched that tutorial you just linked a lot of times. Meanwhile stablediffusion.cpp works as a charm and for free.
