### ISSUE TITLE
FYI: Link to original code implementation under liberal license

### ISSUE THREAD

**Issue by megagrump** [symisc/tiny-dream#9]
The code in this repository was mostly copied from one or both of the following repositories, with the original license and author's names removed without notice. The original code is almost identical, but published under a much more liberal license.

https://github.com/fengwang/Stable-Diffusion-NCNN

https://github.com/EdVince/Stable-Diffusion-NCNN

**Comment by symisc** [comment]
Hello, 
     
     
      
     
    
      It is clearly stated on the related Tiny-Dream sections that portion of code are based on Fengwang SD implementation especially diffusion models. 
     
     
      
     
    
    
     
      
       
       
         -- 
        Mrad - Symisc Systems. 
        
       
      
      
       
      
     
    
    
    
     
     
       On Thursday, Oct 19, 2023 at 1:11 PM, megagrump ***@***.***> wrote: 
       
      
      
       
      The code in this repository was mostly copied from one or both of the following repositories, with the original license and author's names removed without notice. The original code is almost identical, but published under a much more liberal license. 
      https://github.com/fengwang/Stable-Diffusion-NCNN 
      https://github.com/EdVince/Stable-Diffusion-NCNN 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/symisc/tiny-dream/issues/9","url": "https://github.com/symisc/tiny-dream/issues/9","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
